
package br.senac.pi3a.ui.form;

import br.senac.pi3a.model.Contato;
import br.senac.pi3a.services.ServiceContato;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author everton
 */
public class Principal extends javax.swing.JFrame {
    public javax.swing.JPanel cardlayout;
    private boolean contatoClicado = false;
    private boolean favoritoClicado = false;
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainerHeader = new javax.swing.JPanel();
        panelHeaderAdicionar = new javax.swing.JPanel();
        btnVoltarContatos = new javax.swing.JButton();
        btnVoltarFavoritos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        panelHeaderPrincipal = new javax.swing.JPanel();
        btnContatos = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        panelAdicionar = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblSobrenome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        separador = new javax.swing.JSeparator();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cboTipoTelefone = new javax.swing.JComboBox<>();
        lblSexo = new javax.swing.JLabel();
        lblSexo1 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        ckbFavorito = new javax.swing.JCheckBox();
        cboSexo = new javax.swing.JComboBox<>();
        panelProcurar = new javax.swing.JPanel();
        scrollProcurar = new javax.swing.JScrollPane();
        tableProcurar = new javax.swing.JTable();
        txtProcurarContato = new javax.swing.JTextField();
        btnProcurarContato = new javax.swing.JButton();
        panelFavoritos = new javax.swing.JPanel();
        scrollFavoritos = new javax.swing.JScrollPane();
        tableFavorito = new javax.swing.JTable();
        txtProcurarFavorito = new javax.swing.JTextField();
        btnProcurarFavorito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(201, 223, 255));
        setMinimumSize(new java.awt.Dimension(485, 560));

        panelContainerHeader.setLayout(new java.awt.CardLayout());

        panelHeaderAdicionar.setBackground(new java.awt.Color(201, 223, 255));

        btnVoltarContatos.setBackground(new java.awt.Color(25, 169, 147));
        btnVoltarContatos.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnVoltarContatos.setForeground(new java.awt.Color(55, 64, 77));
        btnVoltarContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_md.png"))); // NOI18N
        btnVoltarContatos.setText("Contatos");
        btnVoltarContatos.setBorder(null);
        btnVoltarContatos.setBorderPainted(false);
        btnVoltarContatos.setContentAreaFilled(false);
        btnVoltarContatos.setFocusPainted(false);
        btnVoltarContatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltarContatos.setMaximumSize(new java.awt.Dimension(58, 69));
        btnVoltarContatos.setMinimumSize(new java.awt.Dimension(58, 69));
        btnVoltarContatos.setPreferredSize(new java.awt.Dimension(58, 69));
        btnVoltarContatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltarContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarContatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarContatosMouseExited(evt);
            }
        });

        btnVoltarFavoritos.setBackground(new java.awt.Color(25, 169, 147));
        btnVoltarFavoritos.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnVoltarFavoritos.setForeground(new java.awt.Color(55, 64, 77));
        btnVoltarFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_md.png"))); // NOI18N
        btnVoltarFavoritos.setText("Favoritos");
        btnVoltarFavoritos.setBorder(null);
        btnVoltarFavoritos.setContentAreaFilled(false);
        btnVoltarFavoritos.setFocusPainted(false);
        btnVoltarFavoritos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltarFavoritos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltarFavoritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarFavoritosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarFavoritosMouseEntered(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar_xs.png"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar_xs.png"))); // NOI18N
        btnSalvar.setBorderPainted(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderAdicionarLayout = new javax.swing.GroupLayout(panelHeaderAdicionar);
        panelHeaderAdicionar.setLayout(panelHeaderAdicionarLayout);
        panelHeaderAdicionarLayout.setHorizontalGroup(
            panelHeaderAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarFavoritos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        panelHeaderAdicionarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnVoltarContatos, btnVoltarFavoritos});

        panelHeaderAdicionarLayout.setVerticalGroup(
            panelHeaderAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderAdicionarLayout.createSequentialGroup()
                .addGroup(panelHeaderAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHeaderAdicionarLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelHeaderAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelHeaderAdicionarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelHeaderAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltarContatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnVoltarFavoritos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );

        panelContainerHeader.add(panelHeaderAdicionar, "cardHeaderAdicionar");

        panelHeaderPrincipal.setBackground(new java.awt.Color(201, 223, 255));

        btnContatos.setBackground(new java.awt.Color(25, 169, 147));
        btnContatos.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnContatos.setForeground(new java.awt.Color(55, 64, 77));
        btnContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_md.png"))); // NOI18N
        btnContatos.setText("Contatos");
        btnContatos.setBorder(null);
        btnContatos.setBorderPainted(false);
        btnContatos.setContentAreaFilled(false);
        btnContatos.setDisabledIcon(null);
        btnContatos.setFocusPainted(false);
        btnContatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContatosMouseExited(evt);
            }
        });
        btnContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContatosActionPerformed(evt);
            }
        });

        btnFavoritos.setBackground(new java.awt.Color(25, 169, 147));
        btnFavoritos.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnFavoritos.setForeground(new java.awt.Color(55, 64, 77));
        btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_md.png"))); // NOI18N
        btnFavoritos.setText("Favoritos");
        btnFavoritos.setBorder(null);
        btnFavoritos.setBorderPainted(false);
        btnFavoritos.setContentAreaFilled(false);
        btnFavoritos.setFocusPainted(false);
        btnFavoritos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFavoritos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFavoritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFavoritosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFavoritosMouseEntered(evt);
            }
        });
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adicionar_xs.png"))); // NOI18N
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.setDefaultCapable(false);
        btnAdicionar.setDisabledIcon(null);
        btnAdicionar.setDisabledSelectedIcon(null);

        btnDeletar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deletar_xs.png"))); // NOI18N
        btnDeletar.setBorderPainted(false);

        javax.swing.GroupLayout panelHeaderPrincipalLayout = new javax.swing.GroupLayout(panelHeaderPrincipal);
        panelHeaderPrincipal.setLayout(panelHeaderPrincipalLayout);
        panelHeaderPrincipalLayout.setHorizontalGroup(
            panelHeaderPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnContatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(163, 163, 163)
                .addComponent(btnAdicionar)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHeaderPrincipalLayout.setVerticalGroup(
            panelHeaderPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnFavoritos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelHeaderPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        panelContainerHeader.add(panelHeaderPrincipal, "cardHeaderPrincipal");

        panelMain.setLayout(new java.awt.CardLayout());

        panelAdicionar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 15), new java.awt.Color(55, 64, 77))); // NOI18N
        panelAdicionar.setForeground(new java.awt.Color(55, 64, 77));

        lblNome.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblNome.setForeground(new java.awt.Color(55, 64, 77));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("* Nome");

        lblSobrenome.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(55, 64, 77));
        lblSobrenome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSobrenome.setText("* Sobrenome");

        txtNome.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtNome.setForeground(new java.awt.Color(55, 64, 77));
        txtNome.setText("Everton");
        txtNome.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtNome.setSelectionColor(new java.awt.Color(255, 187, 0));

        txtSobrenome.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtSobrenome.setForeground(new java.awt.Color(55, 64, 77));
        txtSobrenome.setText("Roberto");
        txtSobrenome.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtSobrenome.setSelectionColor(new java.awt.Color(255, 187, 0));

        separador.setBackground(new java.awt.Color(55, 64, 77));
        separador.setForeground(new java.awt.Color(55, 64, 77));

        lblTelefone.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(55, 64, 77));
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefone.setText("* Telefone");

        txtTelefone.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(55, 64, 77));
        txtTelefone.setText("(11) 5515-2677");
        txtTelefone.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtTelefone.setSelectionColor(new java.awt.Color(255, 187, 0));

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(55, 64, 77));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("E-mail");

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(55, 64, 77));
        txtEmail.setText("everton_roliveira@outlook.com");
        txtEmail.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtEmail.setSelectionColor(new java.awt.Color(255, 187, 0));

        cboTipoTelefone.setEditable(true);
        cboTipoTelefone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        cboTipoTelefone.setForeground(new java.awt.Color(55, 64, 77));
        cboTipoTelefone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Celular", "Trabalho" }));

        lblSexo.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(55, 64, 77));
        lblSexo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSexo.setText("* Sexo");

        lblSexo1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblSexo1.setForeground(new java.awt.Color(55, 64, 77));
        lblSexo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSexo1.setText("* Data de nascimento");

        txtDataNascimento.setForeground(new java.awt.Color(55, 64, 77));
        txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataNascimento.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtDataNascimento.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtDataNascimento.setSelectionColor(new java.awt.Color(255, 187, 0));

        ckbFavorito.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ckbFavorito.setForeground(new java.awt.Color(255, 187, 0));
        ckbFavorito.setText("Favorito");

        cboSexo.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        cboSexo.setForeground(new java.awt.Color(55, 64, 77));
        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Feminino", "Masculino" }));

        javax.swing.GroupLayout panelAdicionarLayout = new javax.swing.GroupLayout(panelAdicionar);
        panelAdicionar.setLayout(panelAdicionarLayout);
        panelAdicionarLayout.setHorizontalGroup(
            panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblTelefone)
                    .addComponent(lblSobrenome)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(txtSobrenome))
                .addContainerGap())
            .addGroup(panelAdicionarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ckbFavorito)
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(panelAdicionarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo1)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAdicionarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cboTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAdicionarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtEmail)
                .addGap(12, 12, 12))
        );
        panelAdicionarLayout.setVerticalGroup(
            panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSobrenome)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(lblSexo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbFavorito)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelAdicionarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboSexo, txtDataNascimento});

        panelAdicionarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboTipoTelefone, txtTelefone});

        panelMain.add(panelAdicionar, "cardAdicionar");
        panelAdicionar.getAccessibleContext().setAccessibleName("cardAdicionar");

        tableProcurar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tableProcurar.setForeground(new java.awt.Color(55, 64, 77));
        tableProcurar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableProcurar.setRowHeight(30);
        tableProcurar.setSelectionBackground(new java.awt.Color(201, 223, 255));
        tableProcurar.setSelectionForeground(new java.awt.Color(55, 64, 77));
        tableProcurar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollProcurar.setViewportView(tableProcurar);

        txtProcurarContato.setForeground(new java.awt.Color(135, 128, 128));
        txtProcurarContato.setText("Procurar...");
        txtProcurarContato.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtProcurarContato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProcurarContatoMouseClicked(evt);
            }
        });

        btnProcurarContato.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnProcurarContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurar.png"))); // NOI18N
        btnProcurarContato.setBorderPainted(false);
        btnProcurarContato.setContentAreaFilled(false);
        btnProcurarContato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProcurarContatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProcurarContatoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelProcurarLayout = new javax.swing.GroupLayout(panelProcurar);
        panelProcurar.setLayout(panelProcurarLayout);
        panelProcurarLayout.setHorizontalGroup(
            panelProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcurarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGroup(panelProcurarLayout.createSequentialGroup()
                        .addComponent(txtProcurarContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelProcurarLayout.setVerticalGroup(
            panelProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProcurarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProcurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProcurarContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurarContato, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        panelProcurarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnProcurarContato, txtProcurarContato});

        panelMain.add(panelProcurar, "cardProcurar");
        panelProcurar.getAccessibleContext().setAccessibleName("cardProcurar");

        tableFavorito.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tableFavorito.setForeground(new java.awt.Color(55, 64, 77));
        tableFavorito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "Favorito"
            }
        ));
        tableFavorito.setRowHeight(30);
        tableFavorito.setSelectionBackground(new java.awt.Color(201, 223, 255));
        tableFavorito.setSelectionForeground(new java.awt.Color(55, 64, 77));
        scrollFavoritos.setViewportView(tableFavorito);
        if (tableFavorito.getColumnModel().getColumnCount() > 0) {
            tableFavorito.getColumnModel().getColumn(0).setHeaderValue("Nome");
            tableFavorito.getColumnModel().getColumn(1).setHeaderValue("Telefone");
            tableFavorito.getColumnModel().getColumn(2).setMinWidth(70);
            tableFavorito.getColumnModel().getColumn(2).setPreferredWidth(70);
            tableFavorito.getColumnModel().getColumn(2).setMaxWidth(70);
            tableFavorito.getColumnModel().getColumn(2).setHeaderValue("Favorito");
        }

        txtProcurarFavorito.setForeground(new java.awt.Color(135, 128, 128));
        txtProcurarFavorito.setText("Procurar favorito...");
        txtProcurarFavorito.setMargin(new java.awt.Insets(5, 10, 5, 10));
        txtProcurarFavorito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProcurarFavoritoMouseClicked(evt);
            }
        });

        btnProcurarFavorito.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnProcurarFavorito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurar.png"))); // NOI18N
        btnProcurarFavorito.setBorderPainted(false);
        btnProcurarFavorito.setContentAreaFilled(false);
        btnProcurarFavorito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProcurarFavoritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProcurarFavoritoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelFavoritosLayout = new javax.swing.GroupLayout(panelFavoritos);
        panelFavoritos.setLayout(panelFavoritosLayout);
        panelFavoritosLayout.setHorizontalGroup(
            panelFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFavoritosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGroup(panelFavoritosLayout.createSequentialGroup()
                        .addComponent(txtProcurarFavorito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurarFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFavoritosLayout.setVerticalGroup(
            panelFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFavoritosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProcurarFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurarFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        panelFavoritosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnProcurarFavorito, txtProcurarFavorito});

        panelMain.add(panelFavoritos, "cardFavoritos");
        panelFavoritos.getAccessibleContext().setAccessibleName("cardFavoritos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContainerHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelContainerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // **************MÉTODOS ***************
    
        //Insere Contato
    public void insereContato() throws ParseException{
        if (camposPreenchidos()) {
            Contato contato = new Contato();
            contato.setNome(txtNome.getText() + " " + txtSobrenome.getText());
            contato.setTelefone(txtTelefone.getText());
            contato.setTipoTelefone(cboTipoTelefone.getSelectedIndex());
            contato.setEmail(txtEmail.getText());
            // Seta a letra de acordo com o sexo selecionado
            contato.setSexo(cboSexo.getSelectedIndex());
{
                
            }
            
            // Data de Nascimento
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date data = formato.parse(txtDataNascimento.getText());
            contato.setDataNascimento(data);
            

            // seta favorito se acaso o ckbFavorito estiver selecionado
            if (ckbFavorito.isSelected()) {
                contato.setFavorito(true);
            }
            try {
                ServiceContato.inserirContato(contato);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(rootPane, "Contato inserido com sucesso!!",
                    "Cadastro efetuado", JOptionPane.INFORMATION_MESSAGE);
                    
        }else{
            JOptionPane.showMessageDialog(rootPane,"Preencha os campos marcados com (*)!!!");
        }
            

    }
    
    // Verifica se os campos marcados com (*) estão preenchidos
    public boolean camposPreenchidos(){
        if (txtNome.getText().equals("")) {
            return false;
        }
        if (txtSobrenome.getText().equals("")) {
            return false;
        }
        if (txtTelefone.getText().equals("")) {
            return false;
        }
        if (txtDataNascimento.getText().equals("")) {
            return false;
        }
        return cboSexo.getSelectedIndex() != 0;
    }
    
    // Limpa os campos
    public void limpaCampos(){
        txtNome.setText("");
        txtSobrenome.setText("");
        txtTelefone.setText("");
        cboTipoTelefone.setSelectedIndex(0);
        txtEmail.setText("");
        cboSexo.setSelectedIndex(0);
        txtDataNascimento.setText("");   
    }
    
    
    
    
    
    
    
    
    
    
    private void btnContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContatosActionPerformed
        if (!contatoClicado) {
            btnContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_ativo_md.png")));
            btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_md.png")));
            contatoClicado = true;
            favoritoClicado = false;
        }
    }//GEN-LAST:event_btnContatosActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        if (!favoritoClicado) {
            btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_ativo_md.png")));
            btnContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_md.png")));
            favoritoClicado = true;
            contatoClicado = false;
        }
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void btnContatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContatosMouseEntered
        if (!contatoClicado) {
            btnContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_ativo_md.png")));
        }
    }//GEN-LAST:event_btnContatosMouseEntered

    private void btnContatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContatosMouseExited
        if (!contatoClicado) {
            btnContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_md.png")));
        }
    }//GEN-LAST:event_btnContatosMouseExited

    private void btnFavoritosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFavoritosMouseEntered
        if (!favoritoClicado) {
            btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_ativo_md.png")));
        }
    }//GEN-LAST:event_btnFavoritosMouseEntered

    private void btnFavoritosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFavoritosMouseExited
        if (!favoritoClicado) {
            btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_md.png")));
        }
    }//GEN-LAST:event_btnFavoritosMouseExited

    private void btnVoltarContatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarContatosMouseEntered
        btnVoltarContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_ativo_md.png")));
    }//GEN-LAST:event_btnVoltarContatosMouseEntered

    private void btnVoltarContatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarContatosMouseExited
        btnVoltarContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contato_md.png")));
    }//GEN-LAST:event_btnVoltarContatosMouseExited

    private void btnVoltarFavoritosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarFavoritosMouseEntered
        btnVoltarFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_ativo_md.png")));
    }//GEN-LAST:event_btnVoltarFavoritosMouseEntered

    private void btnVoltarFavoritosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarFavoritosMouseExited
        btnVoltarFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favorito_md.png")));
    }//GEN-LAST:event_btnVoltarFavoritosMouseExited

    private void btnProcurarFavoritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarFavoritoMouseEntered
        btnProcurarFavorito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurar_ativo.png")));
    }//GEN-LAST:event_btnProcurarFavoritoMouseEntered

    private void btnProcurarFavoritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarFavoritoMouseExited
        btnProcurarFavorito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurar.png")));
    }//GEN-LAST:event_btnProcurarFavoritoMouseExited

    private void btnProcurarContatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarContatoMouseEntered
        btnProcurarContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurar_ativo.png")));
    }//GEN-LAST:event_btnProcurarContatoMouseEntered

    private void btnProcurarContatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarContatoMouseExited
        btnProcurarContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/procurar.png")));
    }//GEN-LAST:event_btnProcurarContatoMouseExited

    private void txtProcurarContatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProcurarContatoMouseClicked
        if (txtProcurarContato.getText().equalsIgnoreCase("Procurar...")) {
            txtProcurarContato.setText("");
        }
    }//GEN-LAST:event_txtProcurarContatoMouseClicked

    private void txtProcurarFavoritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProcurarFavoritoMouseClicked
        if (txtProcurarContato.getText().equalsIgnoreCase("Procurar favorito...")) {
            txtProcurarContato.setText("");
        }
    }//GEN-LAST:event_txtProcurarFavoritoMouseClicked

    // btn Salvar
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            insereContato();
            limpaCampos();
        } catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    
    // btn Cancelar
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContatos;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnProcurarContato;
    private javax.swing.JButton btnProcurarFavorito;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltarContatos;
    private javax.swing.JButton btnVoltarFavoritos;
    private javax.swing.JComboBox<String> cboSexo;
    private javax.swing.JComboBox<String> cboTipoTelefone;
    private javax.swing.JCheckBox ckbFavorito;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSexo1;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel panelAdicionar;
    private javax.swing.JPanel panelContainerHeader;
    private javax.swing.JPanel panelFavoritos;
    private javax.swing.JPanel panelHeaderAdicionar;
    private javax.swing.JPanel panelHeaderPrincipal;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelProcurar;
    private javax.swing.JScrollPane scrollFavoritos;
    private javax.swing.JScrollPane scrollProcurar;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tableFavorito;
    private javax.swing.JTable tableProcurar;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProcurarContato;
    private javax.swing.JTextField txtProcurarFavorito;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
